---
- hosts: all
  become: yes
  tasks:
  - name: DISABLED SELINUX
    selinux:
      state: disabled
  - name: DISABLE FIREWALLD
    systemd:
      name: firewalld
      enabled: no
  - name: UPGRADE DI TUTTI I PACCHETTI
    yum:
      name: '*'
      state: latest
  - name: RIAVVIO
    reboot:
      post_reboot_delay: 60
