---
- hosts: all
  become: yes
  tasks:
  - name: DISABLED SELINUX
    selinux:
      state: disabled
  - name: DISABLE FIREWALLD
    systemd:
      name: firewalld
      enabled: no
  - name: UPGRADE DI TUTTI I PACCHETTI
    yum:
      name: '*'
      state: latest
  - name: AGGIUNGE EPEL
    yum:
      name: oracle-epel-release-el8
  - name: AGGIUNGE PACCHETTI
    yum:
      name:
        - htop 
        - cifs-utils 
        - tigervnc-server 
        - tigervnc-server-module 
        - postfix 
        - mailx 
        - net-tools 
        - wget 
        - pv 
        - vnstat 
        - ntfs-3g
      state: latest
  - name: CHRONY PER ORARIO
    yum:
      name: chrony
      state: latest
  - name: TEST 
    systemd:
      name: chronyd
      enabled: yes
  - name: RIAVVIO
    reboot:
      post_reboot_delay: 60
