---
- hosts: test
  become: yes
  tasks:
  - name: disable selinux
    selinux:
     state: disabled
  - name: upgrade all package
    dnf:
      name: '*'
      state: latest
  - name: reboot host
    reboot:
      reboot_timeout: 100
