---
- hosts: test
  become: yes
  tasks:
  - name: DISABLED SELINUX
    selinux:
     state: disabled
  - name: UPGRADE DI TUTTI I PACCHETTI
    dnf:
      name: '*'
      state: latest
  - name: DISABLE FIREWALLD e NetworkManager
    systemd:
      name: firewalld, NetworkManager
      enabled: no
  - name: RIAVVIO
    reboot:
      post_reboot_delay: 90
